### ISSUE TITLE
URL not found when using properties file 

### ISSUE THREAD

**Issue by internetuser2008** [liquibase/docker#59] opened 2021-04-14 23:39 UTC
```
root@host1:~/db1local# docker run --rm -v /root/db1local:/liquibase/changelog liquibase/liquibase --changeLogFile="dbchangelog.xml" --defaultsFile=/root/db1local/liquibase.docker.properties update
Liquibase Community 4.3.2 by Datical
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 23:29:35 (version 4.3.2 #44 built at 2021-03-23 14:01+0000)
Errors:
  **The option --url is required.**

root@host1:~/db1local#
root@host1:~/db1local#
root@host1:~/db1local#
root@host1:~/db1local# pwd
/root/db1local
root@host1:~/db1local# ls -al
total 24
drwxrwxrwx  4 root root  122 Apr 14 23:29 .
drwx------ 12 root root 4096 Apr 14 23:29 ..
-rwxrwxrwx  1 root root  164 Apr 13 19:45 1
drwxrwxrwx  2 root root   64 Apr 14 15:51 base
drwxrwxrwx  2 root root   35 Apr 13 21:15 data
-rwxrwxrwx  1 root root  410 Apr 13 19:45 dbchangelog.xml
-rwxrwxrwx  1 root root  187 Apr 14 23:29 liquibase.docker.properties
root@host1:~/db1local# cat liquibase.docker.properties
classpath: /liquibase/changelog
url: jdbc:postgresql://192.168.1.20:5432/testdb?currentSchema=public
changeLogFile: /root/db1local/dbchangelog.xml
username: user1l
password: user1l

```

**Comment by RafaelWO** [comment] 2021-04-27 11:47
I cannot reproduce your error. But you could try removing the option `--changeLogFile="dbchangelog.xml"` because it is mentioned in the `liquibase.docker.properties` anyway.

P.S. I am not from Liquibase

**Comment by r2liquibase** [comment] 2021-04-30 13:05
Thanks, @RafaelWO . Did that help @internetuser2008 ?

**Comment by RafaelWO** [comment] 2021-04-30 14:25
Actually, the path to the defaults file `--defaultsFile=/root/db1local/liquibase.docker.properties` might be the issue.

Try to pass the absolute path within the docker container which you bound to `/liquibase/changelog`, i.e. `--defaultsFile=/liquibase/changelog/liquibase.docker.properties`, could solve your problem.

This is also done in the [examples in the README](https://github.com/liquibase/docker#using-a-properties-file).

**Comment by r2liquibase** [comment] 2021-05-05 15:27
Thanks @RafaelWO . Your PR is merged so closing this issue.

**Closed by r2liquibase** 2021-05-05 15:27 UTC

**Comment by RafaelWO** [comment] 2021-05-05 16:37
@r2liquibase As my PR is not related to this issue, I'm not sure whether it resolved this issue as well. 

Was this accidentally closed? :thinking:
